version: '3.8'

services:
  postgres:
    image: postgres
    container_name: library_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"

